config/routes.rb
Roofer::Application.routes.draw do

  get "geomongo/index"

  get 'dashboard/index'

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
  end

  match 'updates' => 'updates#index'
  match 'about' => 'about#index'

  resources :roofs do
    resources :photos, module: 'roof'
    resources :statuses, module: 'roof'

    member do
      match 'buy' => 'roofs#buy'
      match 'like' => 'roofs#like'
      match 'dislike' => 'roofs#dislike'
      match 'bookmark' => 'roofs#bookmark'

      match 'instruction' => 'roofs#instruction'
    end
  end

  devise_for :users, :controllers => {
      :omniauth_callbacks => "users/omniauth_callbacks"
  }
  resources :users, :only => [:index, :destroy, :show]

  root to: "home#index"

  match 'balance' => 'balance#index'
  match 'balance/pay' => 'balance#pay'

  scope 'robokassa' do
    match 'paid'    => 'robokassa#paid',    :as => :robokassa_paid    # to handle Robokassa push request
    match 'success' => 'robokassa#success', :as => :robokassa_success # to handle Robokassa success redirect
    match 'fail'    => 'robokassa#fail',    :as => :robokassa_fail    # to handle Robokassa fail redirect
  end

end

app/models/roof.rb
class Roof
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :description, type: String

  field :location, :type => Array, :default => [0, 0]

  field :city, type: String
  field :state, type: String
  field :address, type: String

  field :cost, type: Integer, :default => 0

  field :status, type: Boolean
  field :checked_at, type: Time

  embeds_many :statuses, class_name: 'Roof::Status', cascade_callbacks: true
  embeds_many :photos, class_name: 'Roof::Photo', cascade_callbacks: true
  embeds_one :instruction, class_name: 'Roof::Instruction', cascade_callbacks: true
  belongs_to :user


  accepts_nested_attributes_for :instruction
  accepts_nested_attributes_for :statuses

  index({:location => "2d"}, { min: -200, max: 200 })

  def latitude
    location[0]
  end

  def latitude=( lat )
    self.location = [lat.to_f, self.location[1]]
  end

  def longitude
    location[1]
  end

  def longitude=( lng )
    self.location = [self.location[0], lng.to_f]
  end

  attr_accessible :steps_attributes, :photos_attributes, :instruction_attributes, :statuses_attributes, :user_id,
                  :status, :checked_at,
                  :location, :latitude, :longitude, :name, :city, :state, :address, :description, :cost, :instruction
end

app/models/roof/instruction.rb
class Roof::Instruction
  include Mongoid::Document

  embeds_many :steps, class_name: 'Roof::Step', cascade_callbacks: true
  accepts_nested_attributes_for :steps, allow_destroy: true

  belongs_to :user
  embedded_in :roof, inverse_of: :instructions
end

app/models/roof/photo.rb
class Roof::Photo
  include Rails.application.routes.url_helpers
  include Mongoid::Document
  include Mongoid::Timestamps

  attr_accessible :image, :image_cache, :user_id

  mount_uploader :image, PhotoUploader

  embedded_in :roof, inverse_of: :photos
  belongs_to :user

  #one convenient method to pass jq_upload the necessary information
  def to_jq_upload
    {
        "name" => read_attribute(:image),
        "size" => image.size,
        "url" => image.url,
        "thumbnail_url" => image.thumb.url,
        "delete_url" => roof_photo_path(roof, _id),
        "delete_type" => "DELETE"
    }
  end
end

app/models/roof/status.rb
class Roof::Status
  include Mongoid::Document

  attr_accessible :status, :checked_at, :note, :image, :image_cache, :user_id

  field :status, type: Boolean
  field :checked_at, type: Time
  field :note, type: String
  mount_uploader :image, ImageUploader

  embedded_in :roof, inverse_of: :statuses
  belongs_to :user
end

app/models/roof/step.rb
class Roof::Step
  include Mongoid::Document

  attr_accessible :description, :image, :image_cache

  field :description, type: String
  mount_uploader :image, ImageUploader

  embedded_in :instruction, inverse_of: :steps
end

app/controllers/roof/photos_controller.rb
class Roof::PhotosController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource class: 'Roof::Photo'

  # GET /photos
  # GET /photos.json
  def index
    @roof = Roof.find(params[:roof_id])
    @photos = @roof.photos

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos.where(:user_id => current_user._id).collect { |p| p.to_jq_upload }.to_json }
      #format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
=begin
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end
=end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @roof = Roof.find(params[:roof_id])
    @photo = @roof.photos.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @roof }
    end
  end

  # GET /photos/1/edit
=begin
  def edit
    @photo = Photo.find(params[:id])
  end
=end

  # POST /photos
  # POST /photos.json
  def create
    @roof = Roof.find(params[:roof_id])
    @photo = @roof.photos.new(params[:roof_photo])
    @photo.user = current_user

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: { :files => [@photo.to_jq_upload]}, status: :created, location: roof_photo_path(@roof, @photo) }
        #format.json { render json: @photo, status: :created, location: @photo }

      else
        format.html { render action: "new" }
        format.json { render json: @photo.to_jq_upload.merge({ :error => "custom_failure" }) }
        #format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
=begin
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end
=end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @roof = Roof.find(params[:roof_id])
    @photo = @roof.photos.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to roof_photos_url }
      format.json { render json: true }
    end
  end


end

app/controllers/roof/statuses_controller.rb
# encoding: utf-8

class Roof::StatusesController < ApplicationController
  # GET /roof/statuses
  # GET /roof/statuses.json
  def index
    @roof = Roof.find(params[:roof_id])
    @statuses = @roof.statuses
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /roof/statuses/1
  # GET /roof/statuses/1.json
  def show
    @roof = Roof.find(params[:roof_id])
    @status = @roof.statuses.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /roof/statuses/new
  # GET /roof/statuses/new.json
  def new
    @roof = Roof.find(params[:roof_id])
    @status = @roof.statuses.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /roof/statuses/1/edit
  def edit
    @roof = Roof.find(params[:roof_id])
    @status = @roof.statuses.find(params[:id])
  end

  # POST /roof/statuses
  # POST /roof/statuses.json
  def create
    @roof = Roof.find(params[:roof_id])
    @status = @roof.statuses.new(params[:roof_status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @roof, notice: 'Спасибо что помогаете нам! Заявка отправлена на модерацию :)' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roof/statuses/1
  # PUT /roof/statuses/1.json
  def update
    @roof = Roof.find(params[:roof_id])
    @status = @roof.statuses.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:roof_status])
        format.html { redirect_to @roof, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roof/statuses/1
  # DELETE /roof/statuses/1.json
  def destroy
    @roof = Roof.find(params[:roof_id])
    @status = @roof.statuses.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuseses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/roofs_controller.rb
class RoofsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  load_and_authorize_resource
  layout "roof", :only => :show


  # GET /roofs
  # GET /roofs.json
  def index
    @roofs = Roof.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roofs }
    end
  end

  # GET /roofs/1
  # GET /roofs/1.json
  def show
    @roof = Roof.find(params[:id])
    @roofs_near = Roof.where(:id.ne => @roof._id).geo_near([@roof.latitude, @roof.longitude]).max_distance(1.fdiv(111.12)).first(10)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @roof }
    end
  end

  # GET /roofs/new
  # GET /roofs/new.json
  def new
    @roof = Roof.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @roof }
    end
  end

  # GET /roofs/1/edit
  def edit
    @roof = Roof.find(params[:id])
  end

  # POST /roofs
  # POST /roofs.json
  def create
    @roof = Roof.new(params[:roof])
    @roof.user = current_user

    respond_to do |format|
      if @roof.save
        format.html { redirect_to @roof, notice: 'Roof was successfully created.' }
        format.json { render json: @roof, status: :created, location: @roof }
      else
        format.html { render action: "new" }
        format.json { render json: @roof.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roofs/1
  # PUT /roofs/1.json
  def update
    @roof = Roof.find(params[:id])

    respond_to do |format|
      if @roof.update_attributes(params[:roof])
        format.html { redirect_to @roof, notice: 'Roof was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @roof.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roofs/1
  # DELETE /roofs/1.json
  def destroy
    @roof = Roof.find(params[:id])
    @roof.destroy

    respond_to do |format|
      format.html { redirect_to roofs_url }
      format.json { head :no_content }
    end
  end

  # GET /roofs/1/instruction
  def instruction
    @roof = Roof.find(params[:id])
    authorize! :instruction, @roof
    @roof.build_instruction unless @roof.instruction?

    if @roof.instruction.user? and @roof.instruction.user != current_user
      redirect_to @roof
    end
  end

  # GET /roofs/1/buy
  def buy
    authorize! :buy, Roof
    @roof = Roof.find(params[:id])
    transaction = Transaction.new(amount: -@roof.cost, user: current_user, target_id: @roof._id, target_type: 'roof')

    respond_to do |format|
      if transaction.save
        current_user.roofs << @roof
        if current_user.save
          Transaction.create(amount: @roof.cost - (@roof.cost * 0.25), user: current_user, target_id: @roof._id, target_type: 'roof')
        end

        format.html { redirect_to @roof, notice: 'Roof was bought.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @roof, notice: "Roof wasn't bought." }
        format.json { render json: @roof.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /roofs/1/like
  def like
    authorize! :like, Roof
    @roof = Roof.find(params[:id])

    if current_user.likes?(@roof)
      respond_to do |format|
        if current_user.unlike(@roof)
          format.html { redirect_to @roof, notice: 'Roof was unliked' }
          format.json { head :no_content }
          format.js   { render :js => "$('#like').removeClass('active');" }
        else
          format.html { redirect_to @roof, notice: "Roof wasn't unliked" }
          format.json { render json: @roof.errors, status: :unprocessable_entity }
          format.js   { render :js => "" }
        end
      end

    else
      respond_to do |format|
        if current_user.like(@roof)
          format.html { redirect_to @roof, notice: 'Roof was liked' }
          format.json { head :no_content }
          format.js   { render :js => "$('#like').addClass('active'); $('#dislike').removeClass('active');" }
        else
          format.html { redirect_to @roof, notice: "Roof wasn't liked" }
          format.json { render json: @roof.errors, status: :unprocessable_entity }
          format.js   { render :js => "" }
        end
      end
    end
  end

  # POST /roofs/1/dislike
  def dislike
    authorize! :dislike, Roof
    @roof = Roof.find(params[:id])

    if current_user.dislikes?(@roof)
      respond_to do |format|
        if current_user.undislike(@roof)
          format.html { redirect_to @roof, notice: 'Roof was undisliked' }
          format.json { head :no_content }
          format.js   { render :js => "$('#dislike').removeClass('active');" }
        else
          format.html { redirect_to @roof, notice: "Roof wasn't undisliked" }
          format.json { render json: @roof.errors, status: :unprocessable_entity }
          format.js   { render :js => "" }
        end
      end

    else
      respond_to do |format|
        if current_user.dislike(@roof)
          format.html { redirect_to @roof, notice: 'Roof was disliked' }
          format.json { head :no_content }
          format.js   { render :js => "$('#dislike').addClass('active'); $('#like').removeClass('active');" }
        else
          format.html { redirect_to @roof, notice: "Roof wasn't disliked" }
          format.json { render json: @roof.errors, status: :unprocessable_entity }
          format.js   { render :js => "" }
        end
      end
    end
  end

  # POST /roofs/1/bookmark
  def bookmark
    authorize! :bookmark, Roof
    @roof = Roof.find(params[:id])

    if current_user.bookmarks?(@roof)
      respond_to do |format|
        if current_user.unbookmark(@roof)
          format.html { redirect_to @roof, notice: 'Roof was bookmarked' }
          format.json { head :no_content }
          format.js   { render :js => "$('#bookmark').removeClass('active');" }
        else
          format.html { redirect_to @roof, notice: "Roof wasn't unbookmarked" }
          format.json { render json: @roof.errors, status: :unprocessable_entity }
          format.js   { render :js => "" }
        end
      end

    else
      respond_to do |format|
        if current_user.bookmark(@roof)
          format.html { redirect_to @roof, notice: 'Roof was bookmarked' }
          format.json { head :no_content }
          format.js   { render :js => "$('#bookmark').addClass('active');" }
        else
          format.html { redirect_to @roof, notice: "Roof wasn't bookmarked" }
          format.json { render json: @roof.errors, status: :unprocessable_entity }
          format.js   { render :js => "" }
        end
      end
    end
  end
end

app/helpers/roof/statuses_helper.rb
module Roof::StatusesHelper
end

app/helpers/roofs_helper.rb
module RoofsHelper
end

app/views/roofs/_form.html.haml
.row-fluid
  .span6
    = form_for @roof, :html => { :multipart => true } do |f|
      - if @roof.errors.any?
        #error_explanation
          %h2= "#{pluralize(@roof.errors.count, "error")} prohibited this roof from being saved:"
          %ul
            - @roof.errors.full_messages.each do |msg|
              %li= msg

      = f.label :name
      = f.text_field :name

      = f.label :description
      = f.text_area :description, :rows => 5, :class => 'input-block-level'

      %fieldset
        %legend Местоположение
        = f.label :city
        = f.text_field :city

        = f.label :state
        = f.text_field :state

        = f.label :address
        = f.text_field :address

        = f.hidden_field :latitude
        = f.hidden_field :longitude

      %fieldset
        %legend Состояние
        = f.label :status, :class => "checkbox" do
          = f.check_box :status
          Крыша открыта

        .input-append.date.form_datetime{"data-date-language" => "#{I18n.locale}", "data-date" => "#{(@roof.checked_at.strftime("%F %H:%M") if @roof.checked_at?)}"}
          = f.text_field :checked_at, :value => (@roof.checked_at.strftime("%F %H:%M") if @roof.checked_at?), :readonly => "", :size => "16"
          %span.add-on
            %i.icon-remove
          %span.add-on
            %i.icon-calendar

        - content_for :end do
          :javascript
            $(".form_datetime").datetimepicker({
                format: "dd MM yyyy - hh:ii",
                autoclose: true,
                todayBtn: true,
                minuteStep: 10,
                pickerPosition: "bottom-left"
            });
  .span6
    Карта
    #map

.form-actions
  = submit_tag 'Сохранить', :class => 'btn btn-primary', :onclick => '$("form[id*=roof]").submit();'

- content_for :end do
  :javascript
     $(document).ready(function(){
      var lat = $('#roof_latitude').val();
      var lng = $('#roof_longitude').val();

      if(lat == 0 || lng == 0) {
        GMaps.geocode({
         address: $('#address').val().trim(),
         callback: function(results, status){
          if(status=='OK'){
           map.fitBounds(results[0].geometry.viewport);
          }
         }
        });
      }

      var map = new GMaps({
        div: '#map',
        lat: lat,
        lng: lng,
        panControl: false,
        streetViewControl: false,
        mapTypeControlOptions: {
          style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
        },
        zoomControlOptions: {
          style: google.maps.ZoomControlStyle.SMALL
        }
      });

      var marker = map.addMarker({
        lat: lat,
        lng: lng,
        animation: google.maps.Animation.DROP,
        draggable: true
      });

      GMaps.on('dragend', marker, function() {
        var latlng = this.getPosition();
        change_position(latlng.lat(), latlng.lng());
      });

      function change_position(lat, lng) {
        $('#roof_latitude').val(lat);
        $('#roof_longitude').val(lng);
      }


      GMaps.on('click', map.map, function(event) {
        var latlng = event.latLng;

        map.setCenter(latlng.lat(), latlng.lng());
        marker.setPosition(new google.maps.LatLng(latlng.lat(), latlng.lng()));
        change_position(latlng.lat(), latlng.lng());
      });


      $('#roof_city, #roof_state, #roof_address').bind('click blur', function(e){
        e.preventDefault();

        var address = $('#roof_city').val().trim() + ', ' + $('#roof_state').val().trim() + ' ,' + $('#roof_address').val().trim();
        GMaps.geocode({
          address: address,
          callback: function(results, status){
            if(status=='OK'){
              var latlng = results[0].geometry.location;

              map.setCenter(latlng.lat(), latlng.lng());
              marker.setPosition(new google.maps.LatLng(latlng.lat(), latlng.lng()));
              change_position(latlng.lat(), latlng.lng());
            }
          }
        });
      });
    });

  :javascript
    $(document).ready(function(){
      $('input[type=file].step_image').bootstrapFileInput();
    });

    $(document).on('nested:fieldAdded', function(event){
        // this field was just inserted into your form
        var field = event.field;
        // it's a jQuery object already! Now you can find date input
        var fileField = field.find('input[type=file].step_image');
        // and activate bootstrapFile on it
        fileField.bootstrapFileInput();
    })

app/views/roofs/edit.html.haml
%h1 Редактирование крыши

= render 'form'

app/views/roofs/index.html.haml
%h1 Listing roofs

%table
  %tr
    %th
    %th
    %th

  - @roofs.each do |roof|
    %tr
      %td= link_to 'Show', roof
      %td= link_to 'Edit', edit_roof_path(roof)
      %td= link_to 'Destroy', roof, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Roof', new_roof_path

app/views/roofs/instruction.html.haml
= nested_form_for @roof, :html => { :multipart => true } do |f|
  - if @roof.errors.any?
    #error_explanation
      %h2= "#{pluralize(@roof.errors.count, "error")} prohibited this roof from being saved:"
      %ul
        - @roof.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend Инструкция
    = f.fields_for :instruction do |i|
      = i.hidden_field :user, :value => current_user._id
      = i.fields_for :steps do |b|
        .row-fluid
          .span2{"data-target" => "#modal-gallery", "data-toggle" => "modal-gallery"}
            - if b.object.image.present?
              = link_to image_tag(b.object.image.url(:thumb)), b.object.image.url(:original), "data-gallery" => "gallery"
            - else
              = b.file_field :image, :class => 'step_image', :title => 'Фотография'
          .span8
            = b.text_area :description, :rows => 3, :class => 'input-block-level'
          .span2
            = b.link_to_remove "Удалить шаг"
      = i.link_to_add "Добавить шаг", :steps

  %fieldset
    %legend Стоимость
    = f.label :cost
    = f.text_field :cost, :class => 'span1'
    %span.help-inline{ :data => { "original-title" => "Валюта руфим", "placement" => "bottom", "toggle" => "tooltip"}}
      %i.icon-white.icon-rocket


  .form-actions
    = submit_tag 'Сохранить', :class => 'btn btn-primary', :onclick => '$("form[id*=roof]").submit();'
    = link_to 'Назад', @roof, :class => 'btn'

- content_for :end do
  :javascript
    $(document).ready(function(){
      $('input[type=file].step_image').bootstrapFileInput();
    });

    $(document).on('nested:fieldAdded', function(event){
        // this field was just inserted into your form
        var field = event.field;
        // it's a jQuery object already! Now you can find date input
        var fileField = field.find('input[type=file].step_image');
        // and activate bootstrapFile on it
        fileField.bootstrapFileInput();
    })

app/views/roofs/new.html.haml
%h1 Новая крыша

= render 'form'