config/routes.rb
Roofer::Application.routes.draw do

  get "geomongo/index"

  get 'dashboard/index'

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
  end

  match 'updates' => 'updates#index'
  match 'about' => 'about#index'

  resources :roofs do
    resources :photos, module: 'roof'
    resources :statuses, module: 'roof'

    member do
      match 'buy' => 'roofs#buy'
      match 'like' => 'roofs#like'
      match 'dislike' => 'roofs#dislike'
      match 'bookmark' => 'roofs#bookmark'

      match 'instruction' => 'roofs#instruction'
    end
  end

  devise_for :users, :controllers => {
      :omniauth_callbacks => "users/omniauth_callbacks"
  }
  resources :users, :only => [:index, :destroy, :show]

  root to: "home#index"

  match 'balance' => 'balance#index'
  match 'balance/pay' => 'balance#pay'

  scope 'robokassa' do
    match 'paid'    => 'robokassa#paid',    :as => :robokassa_paid    # to handle Robokassa push request
    match 'success' => 'robokassa#success', :as => :robokassa_success # to handle Robokassa success redirect
    match 'fail'    => 'robokassa#fail',    :as => :robokassa_fail    # to handle Robokassa fail redirect
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:city]
      @city = City.where(alias: params[:city]).first
    end

    unless @city
      @city = City.first
    end

    @roofs = Roof.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
#map-container
  #map


- content_for :end do
  :javascript
    var roofs = #{raw @roofs.to_json}

    $(document).ready(function(){
      var map = new GMaps({
        div: '#map',
        lat: -12.043333,
        lng: -77.028333,
        panControl: false,
        streetViewControl: false,
        mapTypeControlOptions: {
          position: google.maps.ControlPosition.BOTTOM_CENTER
        },
        zoomControlOptions: {
          position: google.maps.ControlPosition.LEFT_CENTER
        }
      });

      var markers_data = [];
      for (var i = 0; i < roofs.length; i++) {
        var roof = roofs[i];
        if (roof.location != undefined) {
          //var icon = 'https://foursquare.com/img/categories/food/default.png';
          markers_data.push({
            lat : roof.location[0],
            lng : roof.location[1],
            url : '#{roofs_path}/' + roof._id,
            click : function(e) {
              window.location.href = this.url;
            }
            //title : roof.name,
            /*
            icon : {
              size : new google.maps.Size(32, 32),
              url : icon
            }
            */
          });
        }
      }
      map.addMarkers(markers_data);

      /* Местоположение
      GMaps.geolocate({
       success: function(position) {
        map.setCenter(position.coords.latitude, position.coords.longitude);
       },
       error: function(error) {
        alert('Geolocation failed: '+error.message);
       },
       not_supported: function() {
        alert("Your browser does not support geolocation");
       },
       always: function() {
        alert("Done!");
       }
      });
      */

      GMaps.geocode({
       address: $('#address').val().trim(),
       callback: function(results, status){
        if(status=='OK'){
         map.fitBounds(results[0].geometry.viewport);
        }
       }
      });

    });